### ISSUE TITLE
Clean relations.yml ubuntu overwrite

### ISSUE THREAD

**Issue by GHAStVHenry** [utsw-bicf/auto-docker#14]
gudmap-rbk branch:
In initial clean up, I put:
```
  ubuntu:
    20.10:
      children: [null]
      parents: [null]
```
in the relations.yml

I then replaced `children: ['gudmap-rbk_base:1.0.0']`

it got overwritten to:
```
  ubuntu:
    20.1:
      children: [null]
      parents: [null]
    '20.10':
      children: ['gudmap-rbk_base:1.0.0']
      parents: []
```

Removing completely now that gudmap-rbk_base:1.0.0 is pushed
